<a href="https://colab.research.google.com/github/Vikram-0401/Python_Projects/blob/main/Aiml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python libraries

Numpy

In [ ]:
import numpy as np

temperatures = np.array([23.4, 34.5, 34, 34.6, 45])
avg = np.mean(temperatures)
print(avg)



34.3


In [ ]:
import numpy as np

zeros = np.zeros(3)
ones = np.ones(5)
custom = np.full(4, 3)
zeros_2d = np.zeros((2, 3))
print(zeros)
print(ones)
print(custom)
print(zeros_2d)

[0. 0. 0.]
[1. 1. 1. 1. 1.]
[3 3 3 3]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


Numpy array properties

In [ ]:
# shape -> check the dimension of the multi dimension array
import numpy as np

arr_2d = np.array([[2,3],
                   [4,5],
                   [2,5]])
print(arr_2d.shape)

(3, 2)


In [ ]:
# size -> size of the array

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr.size)

5


In [ ]:
# ndim -> Number of dimension

import numpy as np

arr_1d = np.array([1,2,4,5,6])
arr_2d = np.array([[2,3],
                   [4,5],
                   [2,5]])
arr_3d = np.array([[[1,2],
                    [3,4]],
                   [[5,6],
                    [7,8]]])
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)


1
2
3


In [ ]:
# dtype = data type of the element

import numpy as np

arr = np.array([10, 20, 30, 40.5])
print(arr.dtype)

float64


In [ ]:
# astype = converting the types of the data

import numpy as np

arr = np.array([10, 20, 30, 40.5])
print(arr.dtype)
arr = arr.astype(int)
print(arr)
print(arr.dtype)

float64
[10 20 30 40]
int64


In [ ]:
# operations

import numpy as np

arr = np.array([2,3,5,6,6,7])

print(arr + 3)
print(arr * 4)
print(arr ** 2)

[ 5  6  8  9  9 10]
[ 8 12 20 24 24 28]
[ 4  9 25 36 36 49]


In [ ]:
# aggregations

import numpy as np

arr = np.array([2,3,4,5,6,7])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

27
4.5
2
7
1.707825127659933
2.9166666666666665


Indexing & slicing

In [ ]:
# indexing -> Accessing the single element of the list

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[2])
print(arr[-1])


3
5


In [ ]:
# Slicing -> Accessing the subset/subarray of the data

import numpy as np
arr = np.array([10,20,30,40,50])

print(arr[0:5])
print(arr[:4])
print(arr[::2])
print(arr[::-1])

[10 20 30 40 50]
[10 20 30 40]
[10 30 50]
[50 40 30 20 10]


In [ ]:
# Fancing indexing -> Selecting the multiple element in a single time

import numpy as np
arr = np.array([10,20,30,40,50])

print(arr[[0,2,4]])

[10 30 50]


In [ ]:
# Boolean maskin\g -> Selecting the element based on some condition


import numpy as np
arr = np.array([10,20,30,40,50])

print(arr[arr > 20])


[30 40 50]


Reshaping and manipulating

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60])

print(arr.reshape(2,3))

[[10 20 30]
 [40 50 60]]


In [ ]:
# ravel() -> view
# flatten() -> copy

import numpy as np
arr = np.array([[1,2],[3,4]])

print(arr.ravel())
print(arr.flatten())

[1 2 3 4]
[1 2 3 4]


Advanced numpy

In [ ]:
#  insert -> [arr, index, value, axis] axis -> 0 rowwise, 1 -> columnwise

import numpy as np
arr = np.array([10,20,30,40,50])

print(np.insert(arr, 2, 100))

import numpy as np
arr = np.array([[1,2],[3,4]])

print(np.insert(arr, 1, [5,6], axis=0))

[ 10  20 100  30  40  50]
[[1 2]
 [5 6]
 [3 4]]


In [ ]:
# append -> adding the element at the end of the array

import numpy as np
arr = np.array([10,20,30,40,50])

print(np.append(arr, 60))

import numpy as np
arr = np.array([[1,2],[3,4]])

print(np.append(arr, [[5,6]], axis=0))

# Example of vertical stacking
arr1_2d = np.array([[1, 2], [3, 4]])
arr2_2d = np.array([[5, 6]])
print(np.concatenate((arr1_2d, arr2_2d), axis=0))

[10 20 30 40 50 60]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# concatenate -> np.concatenate((arr1, arr2), axis = 0)
# axis -> 0 means vertical stacking
# axis -> 1 mean horizontal stacking

import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.concatenate((arr1, arr2)))
print(np.concatenate((arr1, arr2), axis=0))


[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])

new_arr = print(np.delete(arr, 2))

arr_2d = np.array([[1,2],[3,4]])
new_2d = print(np.delete(arr_2d, 0, axis=0))

[10 20 40 50]
[[3 4]]


In [ ]:
# stacking

import numpy as np

arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

print(np.vstack((arr_1, arr_2)))
print(np.hstack((arr_1, arr_2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60])

print(np.split(arr, 2))

[array([10, 20, 30]), array([40, 50, 60])]


Broadcasting : Broadcasting in NumPy is a mechanism that allows arithmetic operations to be performed on arrays of different shapes and sizes. Instead of requiring arrays to have identical shapes for element-wise operations, NumPy automatically "stretches" or "broadcasts" the smaller array to match the dimensions of the larger array, making them compatible for the operation

In [ ]:
# without broadcasting

prices = [100,200,300,400]
discount = 10

new_prices = []

for price in prices:
  final_price = price - (price * discount/100)
  new_prices.append(final_price)

print(new_prices)

[90.0, 180.0, 270.0, 360.0]


In [ ]:
import numpy as np
prices = np.array([100,200,300,400])
discount = 10

final_prices = prices - (prices * discount/100)
print(final_prices)

[ 90. 180. 270. 360.]


In [ ]:
import numpy as np
arr = np.array([100,200,300,400])
print(arr * 2)

[200 400 600 800]


In [ ]:
import numpy as np
matrix = np.array([[1,2,3], [4,5,6]]) #2*3 matrix
vector = np.array([10,20,30]) #1d array

print(matrix + vector)

[[11 22 33]
 [14 25 36]]


In [ ]:
import numpy as np
matrix = np.array([[1,2,3], [4,5,6]]) #2*3 matrix
vector = np.array([10,20]) #1d array

# print(matrix + vector) # error : ValueError: operands could not be broadcast together with shapes (2,3) (2,)


Handling missing values : To handle the missing value in the data we have 3 builtin functions

np.isnan() -> detect the missing values
np.nan_to_num() -> it replaces the missing values with some other values
np.inf() -> detect the infinte values

In [ ]:
import numpy as np
arr = np.array([1,2,np.nan,4,5,np.nan])

print(np.isnan(arr))

# interview question : Can we compare the to nan values
print(np.nan == np.nan)
# Answer for this is no because we cannot directly compare the 2 nan values

[False False  True False False  True]


In [ ]:
import numpy as np
arr = np.array([1,2,np.nan,4,5,np.nan])

cleaned_arr = np.nan_to_num(arr) # default replacing value is 0
custom_cleaned_arr = np.nan_to_num(arr, nan=100)
print(cleaned_arr)
print(custom_cleaned_arr)

[1. 2. 0. 4. 5. 0.]
[  1.   2. 100.   4.   5. 100.]


In [ ]:
import numpy as np
arr = np.array([1,2,np.inf,4,5,-np.inf])

print(np.isinf(arr))

[False False  True False False  True]


In [ ]:
import numpy as np
arr = np.array([1,2,np.inf,4,5,-np.inf])

cleaned_arr = np.nan_to_num(arr, posinf=1000, neginf=-1000)
print(cleaned_arr)

[    1.     2.  1000.     4.     5. -1000.]


### ***Pandas***

In [ ]:
# pandas is a powerful and popular python library designed for data manipulation ( cleaning, transforming & structuring ) and
# data analysis ( finding patterns, insights and trends ).
# It simplifies working with structured datasets like tables, spreadsheets, or time-series data

In [ ]:
import pandas as pd

df = pd.read_csv('Employee.csv')
print(df)


# similarly we have read_excel() for excel and read_json() for json

# gcsfs library -> we can read the data from the cloud

      Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0     Bachelors         2017  Bangalore            3   34    Male          No   
1     Bachelors         2013       Pune            1   28  Female          No   
2     Bachelors         2014  New Delhi            3   38  Female          No   
3       Masters         2016  Bangalore            3   27    Male          No   
4       Masters         2017       Pune            3   24    Male         Yes   
...         ...          ...        ...          ...  ...     ...         ...   
4648  Bachelors         2013  Bangalore            3   26  Female          No   
4649    Masters         2013       Pune            2   37    Male          No   
4650    Masters         2018  New Delhi            3   27    Male          No   
4651  Bachelors         2012  Bangalore            3   30    Male         Yes   
4652  Bachelors         2015  Bangalore            3   33    Male         Yes   

      ExperienceInCurrentDo

In [ ]:
import pandas as pd

data = {
    "Name": ['Ram', 'seeta', 'Lashman'],
    "Age": [25, 30, 35],
    "Salary": [50000, 60000, 70000]
}

df = pd.DataFrame(data)
print(df)

df.to_csv('output.csv', index=False)
df.to_excel('output.xlsx', index=False)
df.to_json('output.json', index=False)


      Name  Age  Salary
0      Ram   25   50000
1    seeta   30   60000
2  Lashman   35   70000


In [ ]:
# For quick overview we can use the head and tail methods by default it will shows the
# first and last 5 rows of the dataset and we can customise that by passing the value of n.

import pandas as pd

df = pd.read_csv('Employee.csv')

print(df.head())
print(df.tail())
print(df.head(10))
print(df.tail(10))


   Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No   
1  Bachelors         2013       Pune            1   28  Female          No   
2  Bachelors         2014  New Delhi            3   38  Female          No   
3    Masters         2016  Bangalore            3   27    Male          No   
4    Masters         2017       Pune            3   24    Male         Yes   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1  
      Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
4648  Bachelors         2013  Bangalore            3   26  Female          No   
4649    Masters         2013       Pune            2   37    Male          No   
4650    Masters         2018  

In [ ]:
# info() method -> Summarizes the dataset
# 1) tells the number of rows & col 2) Col name 3) type 4) Non null values 5) memory usage of dtatframe

import pandas as pd

df = pd.read_csv('Employee.csv')
print(df.info())



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   Education                  4653 non-null   object
 1   JoiningYear                4653 non-null   int64 
 2   City                       4653 non-null   object
 3   PaymentTier                4653 non-null   int64 
 4   Age                        4653 non-null   int64 
 5   Gender                     4653 non-null   object
 6   EverBenched                4653 non-null   object
 7   ExperienceInCurrentDomain  4653 non-null   int64 
 8   LeaveOrNot                 4653 non-null   int64 
dtypes: int64(5), object(4)
memory usage: 327.3+ KB
None


In [ ]:
import pandas as pd

data = {
    "Name": ['Ram', 'Seeta', 'Lashman', 'Leela', 'Ravi', 'Teju', 'sharan', 'Mani'],
    "Age": [25, 30, 35, 21, 30, 30, 28, 36],
    "Salary": [50000, 60000, 70000, 30000, 400000, 200000, 450000, 48000],
    "Performance": [80,89,90,90,96,98,96,90]
}

df = pd.DataFrame(data)
print(df)

print("Descriptive stats")
print(df.describe())

# Std -> SD : Its the difference between the values and the mean of the column
"""
if the SD is low means we can say that the values are close to the mean and consistent
if the SD is high means we can say that the values are far from the mean and inconsistent
"""

"""
what is 25%, 50% and 75% in this output ?
The answer is

25% (1st Quartile): This is the value below which 25% of the data falls. It's also known as the first quartile.
50% (2nd Quartile): This is the median value of the data. It's the value that divides the dataset in half, with 50% of the data below it and 50% above it.
75% (3rd Quartile): This is the value below which 75% of the data falls. It's also known as the third quartile.

"""

      Name  Age  Salary  Performance
0      Ram   25   50000           80
1    Seeta   30   60000           89
2  Lashman   35   70000           90
3    Leela   21   30000           90
4     Ravi   30  400000           96
5     Teju   30  200000           98
6   sharan   28  450000           96
7     Mani   36   48000           90
Descriptive stats
             Age        Salary  Performance
count   8.000000       8.00000     8.000000
mean   29.375000  163500.00000    91.125000
std     4.897157  170229.25718     5.693041
min    21.000000   30000.00000    80.000000
25%    27.250000   49500.00000    89.750000
50%    30.000000   65000.00000    90.000000
75%    31.250000  250000.00000    96.000000
max    36.000000  450000.00000    98.000000


In [ ]:
import pandas as pd

data = {
    "Name": ['Ram', 'Seeta', 'Lashman', 'Leela', 'Ravi', 'Teju', 'sharan', 'Mani'],
    "Age": [25, 30, 35, 21, 30, 30, 28, 36],
    "Salary": [50000, 60000, 70000, 30000, 400000, 200000, 450000, 48000],
    "Performance": [80,89,90,90,96,98,96,90]
}

df = pd.DataFrame(data)
print(df)
print(f'Shape: {df.shape}')
print(f'Columns: {df.columns}')


      Name  Age  Salary  Performance
0      Ram   25   50000           80
1    Seeta   30   60000           89
2  Lashman   35   70000           90
3    Leela   21   30000           90
4     Ravi   30  400000           96
5     Teju   30  200000           98
6   sharan   28  450000           96
7     Mani   36   48000           90
Shape: (8, 4)
Columns: Index(['Name', 'Age', 'Salary', 'Performance'], dtype='object')


In [ ]:
import pandas as pd

data = {
    "Name": ['Ram', 'Seeta', 'Lashman', 'Leela', 'Ravi', 'Teju', 'sharan', 'Mani'],
    "Age": [25, 30, 35, 21, 30, 30, 28, 36],
    "Salary": [50000, 60000, 70000, 30000, 400000, 200000, 450000, 48000],
    "Performance": [80,89,90,90,96,98,96,90]
}

df = pd.DataFrame(data)
print(df)

# Selecting the single column
print('\n')
print("Name (single column return series)")
print(df['Name'])

# Selecting the multiple column
print('\n')
print("Name & Salary (multiple column return dataframe)")
print(df[['Name', 'Salary']])


      Name  Age  Salary  Performance
0      Ram   25   50000           80
1    Seeta   30   60000           89
2  Lashman   35   70000           90
3    Leela   21   30000           90
4     Ravi   30  400000           96
5     Teju   30  200000           98
6   sharan   28  450000           96
7     Mani   36   48000           90


Name (single column return series)
0        Ram
1      Seeta
2    Lashman
3      Leela
4       Ravi
5       Teju
6     sharan
7       Mani
Name: Name, dtype: object


Name & Salary (multiple column return dataframe)
      Name  Salary
0      Ram   50000
1    Seeta   60000
2  Lashman   70000
3    Leela   30000
4     Ravi  400000
5     Teju  200000
6   sharan  450000
7     Mani   48000


In [ ]:
import pandas as pd

data = {
    "Name": ['Ram', 'Seeta', 'Lashman', 'Leela', 'Ravi', 'Teju', 'sharan', 'Mani'],
    "Age": [25, 30, 35, 21, 30, 30, 28, 36],
    "Salary": [50000, 60000, 70000, 30000, 400000, 200000, 450000, 48000],
    "Performance": [80,89,90,90,96,98,96,90]
}

df = pd.DataFrame(data)
print(df)

# Employee with salary greater than 50000
print('\n Employees with salaray greater than 50000')
print(df[df['Salary'] > 50000])

# Employee with salary greater than 50000 & age > 30
print('\n Employees with salaray greater than 50000 and age > 30')
print(df[(df['Salary'] > 50000) & (df['Age'] >= 30)])

      Name  Age  Salary  Performance
0      Ram   25   50000           80
1    Seeta   30   60000           89
2  Lashman   35   70000           90
3    Leela   21   30000           90
4     Ravi   30  400000           96
5     Teju   30  200000           98
6   sharan   28  450000           96
7     Mani   36   48000           90

 Employees with salaray greater than 50000
      Name  Age  Salary  Performance
1    Seeta   30   60000           89
2  Lashman   35   70000           90
4     Ravi   30  400000           96
5     Teju   30  200000           98
6   sharan   28  450000           96

 Employees with salaray greater than 50000 and age > 30
      Name  Age  Salary  Performance
1    Seeta   30   60000           89
2  Lashman   35   70000           90
4     Ravi   30  400000           96
5     Teju   30  200000           98


# Advanced **Pandas** *italicized text*

In [ ]:
# Modifications -> Adding columns

import pandas as pd

data = {
    "Name": ['Ram', 'Seeta', 'Lashman', 'Leela', 'Ravi', 'Teju', 'sharan', 'Mani'],
    "Age": [25, 30, 35, 21, 30, 30, 28, 36],
    "Salary": [50000, 60000, 70000, 30000, 400000, 200000, 450000, 48000],
    "Performance": [80,89,90,90,96,98,96,90]
}

df = pd.DataFrame(data)
print(df)

df['Bonus'] = df['Salary'] * 0.1
print(df)

# Using insert

# df.insert(loc, column_name, data)

df.insert(0, 'Employee_ID', [10,20,30,40,50,60,70,80])
print(df)

      Name  Age  Salary  Performance
0      Ram   25   50000           80
1    Seeta   30   60000           89
2  Lashman   35   70000           90
3    Leela   21   30000           90
4     Ravi   30  400000           96
5     Teju   30  200000           98
6   sharan   28  450000           96
7     Mani   36   48000           90
      Name  Age  Salary  Performance    Bonus
0      Ram   25   50000           80   5000.0
1    Seeta   30   60000           89   6000.0
2  Lashman   35   70000           90   7000.0
3    Leela   21   30000           90   3000.0
4     Ravi   30  400000           96  40000.0
5     Teju   30  200000           98  20000.0
6   sharan   28  450000           96  45000.0
7     Mani   36   48000           90   4800.0
   Employee_ID     Name  Age  Salary  Performance    Bonus
0           10      Ram   25   50000           80   5000.0
1           20    Seeta   30   60000           89   6000.0
2           30  Lashman   35   70000           90   7000.0
3           40   

In [ ]:
import pandas as pd

data = {
    "Name": ['Ram', 'Seeta', 'Lashman', 'Leela', 'Ravi', 'Teju', 'sharan', 'Mani'],
    "Age": [25, 30, 35, 21, 30, 30, 28, 36],
    "Salary": [50000, 60000, 70000, 30000, 400000, 200000, 450000, 48000],
    "Performance": [80,89,90,90,96,98,96,90]
}

df = pd.DataFrame(data)
print(df)

# update -> df.loc(row_index, col_name)

df.loc[0, 'Salary'] = 70000
print(df)

      Name  Age  Salary  Performance
0      Ram   25   50000           80
1    Seeta   30   60000           89
2  Lashman   35   70000           90
3    Leela   21   30000           90
4     Ravi   30  400000           96
5     Teju   30  200000           98
6   sharan   28  450000           96
7     Mani   36   48000           90
      Name  Age  Salary  Performance
0      Ram   25   70000           80
1    Seeta   30   60000           89
2  Lashman   35   70000           90
3    Leela   21   30000           90
4     Ravi   30  400000           96
5     Teju   30  200000           98
6   sharan   28  450000           96
7     Mani   36   48000           90


In [ ]:
import pandas as pd

data = {
    "Name": ['Ram', 'Seeta', 'Lashman', 'Leela', 'Ravi', 'Teju', 'sharan', 'Mani'],
    "Age": [25, 30, 35, 21, 30, 30, 28, 36],
    "Salary": [50000, 60000, 70000, 30000, 400000, 200000, 450000, 48000],
    "Performance": [80,89,90,90,96,98,96,90]
}

df = pd.DataFrame(data)
print(df)

# remove -> df.drop(columns=['Performance'], inplace=False)

df.drop(columns=['Performance'], inplace=True)
print(df)

      Name  Age  Salary  Performance
0      Ram   25   50000           80
1    Seeta   30   60000           89
2  Lashman   35   70000           90
3    Leela   21   30000           90
4     Ravi   30  400000           96
5     Teju   30  200000           98
6   sharan   28  450000           96
7     Mani   36   48000           90
      Name  Age  Salary
0      Ram   25   50000
1    Seeta   30   60000
2  Lashman   35   70000
3    Leela   21   30000
4     Ravi   30  400000
5     Teju   30  200000
6   sharan   28  450000
7     Mani   36   48000


In [ ]:
# Missing data

import pandas as pd

data = {
    "Name": ['Ram', None, 'Lashman', 'Leela', 'Ravi', 'Teju', 'sharan', 'Mani'],
    "Age": [25, None, 35, 21, 30, 30, 28, 36],
    "Salary": [50000, None, 70000, 30000, 400000, 200000, 450000, 48000],
    "Performance": [80,None,90,90,96,98,96,90]
}

df = pd.DataFrame(data)
print(df)

print(df.isnull())
print(df.isnull().sum())

      Name   Age    Salary  Performance
0      Ram  25.0   50000.0         80.0
1     None   NaN       NaN          NaN
2  Lashman  35.0   70000.0         90.0
3    Leela  21.0   30000.0         90.0
4     Ravi  30.0  400000.0         96.0
5     Teju  30.0  200000.0         98.0
6   sharan  28.0  450000.0         96.0
7     Mani  36.0   48000.0         90.0
    Name    Age  Salary  Performance
0  False  False   False        False
1   True   True    True         True
2  False  False   False        False
3  False  False   False        False
4  False  False   False        False
5  False  False   False        False
6  False  False   False        False
7  False  False   False        False
Name           1
Age            1
Salary         1
Performance    1
dtype: int64


In [ ]:
# Handling the missing values

import pandas as pd

data = {
    "Name": ['Ram', None, 'Lashman', 'Leela', 'Ravi', 'Teju', 'sharan', 'Mani'],
    "Age": [25, 45, 35, 21, 30, 30, 28, 36],
    "Salary": [50000, None, 70000, 30000, 400000, 200000, 450000, 48000],
    "Performance": [80,None,90,90,96,98,96,90]
}

df = pd.DataFrame(data)
print(df)

df.dropna(inplace=True)
print(df)

# In this method it will remove the entire row and column of that missing data
# so if their is frequent occurence then the entire data may vanish

# Handling method 2 using fillna()


import pandas as pd

data = {
    "Name": ['Ram', None, 'Lashman', 'Leela', 'Ravi', 'Teju', 'sharan', 'Mani'],
    "Age": [25, None, 35, 21, 30, 30, 28, 36],
    "Salary": [50000, None, 70000, 30000, 400000, 200000, 450000, 48000],
    "Performance": [80,None,90,90,96,98,96,90]
}

df = pd.DataFrame(data)
print(df)

# df.fillna(0, inplace=True)
"""
print("\n fill the calculated value")
df['Age'].fillna(df['Age'].mean(), inplace=True)
print(df)
"""

      Name  Age    Salary  Performance
0      Ram   25   50000.0         80.0
1     None   45       NaN          NaN
2  Lashman   35   70000.0         90.0
3    Leela   21   30000.0         90.0
4     Ravi   30  400000.0         96.0
5     Teju   30  200000.0         98.0
6   sharan   28  450000.0         96.0
7     Mani   36   48000.0         90.0
      Name  Age    Salary  Performance
0      Ram   25   50000.0         80.0
2  Lashman   35   70000.0         90.0
3    Leela   21   30000.0         90.0
4     Ravi   30  400000.0         96.0
5     Teju   30  200000.0         98.0
6   sharan   28  450000.0         96.0
7     Mani   36   48000.0         90.0
      Name   Age    Salary  Performance
0      Ram  25.0   50000.0         80.0
1     None   NaN       NaN          NaN
2  Lashman  35.0   70000.0         90.0
3    Leela  21.0   30000.0         90.0
4     Ravi  30.0  400000.0         96.0
5     Teju  30.0  200000.0         98.0
6   sharan  28.0  450000.0         96.0
7     Mani  36.0 

'\nprint("\n fill the calculated value")\ndf[\'Age\'].fillna(df[\'Age\'].mean(), inplace=True)\nprint(df)\n'

In [ ]:
# Interpolation -> It fills the missing values with the estimated values

"""
1 - preserve the data integrity
2 - smooth trends
3 - avoid data loss
"""

import pandas as pd

data = {
    "Time": [1,2,3,4,5],
    "Value": [10,None,30,None,50]
}

df = pd.DataFrame(data)
print(df)

df['Value'] = df['Value'].interpolate(method='linear')
print(df)


   Time  Value
0     1   10.0
1     2    NaN
2     3   30.0
3     4    NaN
4     5   50.0
   Time  Value
0     1   10.0
1     2   20.0
2     3   30.0
3     4   40.0
4     5   50.0


Sorting & Aggregation

In [ ]:
import pandas as pd

data = {
    "Name": ['Arun', 'Karun', 'Tarun', 'Sarun', 'Marun'],
    "Age": [25, 30, 35, 25, 30],
    "Salary": [50000, 60000, 70000, 30000, 400000]
}

df = pd.DataFrame(data)

print("\n Desecnding")
df.sort_values(by="Age", ascending=False, inplace=True)
print(df)

print("\n Ascending")
df.sort_values(by="Age", ascending=True, inplace=True)
print(df)

print("\n Sort multiple columns")
df.sort_values(by=['Age', 'Salary'], ascending=[False, True], inplace=True)
print(df)



 Desecnding
    Name  Age  Salary
2  Tarun   35   70000
4  Marun   30  400000
1  Karun   30   60000
0   Arun   25   50000
3  Sarun   21   30000

 Ascending
    Name  Age  Salary
3  Sarun   21   30000
0   Arun   25   50000
1  Karun   30   60000
4  Marun   30  400000
2  Tarun   35   70000

 Sort multiple columns
    Name  Age  Salary
2  Tarun   35   70000
1  Karun   30   60000
4  Marun   30  400000
0   Arun   25   50000
3  Sarun   21   30000


In [ ]:
# Grouping

import pandas as pd

data = {
    "Name": ['Arun', 'Karun', 'Tarun', 'Sarun', 'Marun'],
    "Age": [25, 30, 35, 25, 30],
    "Salary": [50000, 60000, 70000, 30000, 30000]
}

df = pd.DataFrame(data)

grouped = df.groupby(['Age', 'Name'])['Salary'].sum();
print(grouped)


Age  Name 
25   Arun     50000
     Sarun    30000
30   Karun    60000
     Marun    30000
35   Tarun    70000
Name: Salary, dtype: int64


Merging

In [4]:
import pandas as pd

df_customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'David']
})

df_orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104],
    'customer_id': [1, 2, 3, 6]
})

df_merged = pd.merge(df_customers, df_orders, on='customer_id', how='inner')
print("Inner join")
print(df_merged)

df_merged = pd.merge(df_customers, df_orders, on='customer_id', how='left')
print("left join")
print(df_merged)

df_merged = pd.merge(df_customers, df_orders, on='customer_id', how='right')
print("right join")
print(df_merged)

df_merged = pd.merge(df_customers, df_orders, on='customer_id', how='outer')
print("outer join")
print(df_merged)

Inner join
   customer_id     name  order_id
0            1    Alice       101
1            2      Bob       102
2            3  Charlie       103
left join
   customer_id     name  order_id
0            1    Alice     101.0
1            2      Bob     102.0
2            3  Charlie     103.0
3            4    David       NaN
right join
   customer_id     name  order_id
0            1    Alice       101
1            2      Bob       102
2            3  Charlie       103
3            6      NaN       104
outer join
   customer_id     name  order_id
0            1    Alice     101.0
1            2      Bob     102.0
2            3  Charlie     103.0
3            4    David       NaN
4            6      NaN     104.0


In [7]:
import pandas as pd

df_region1 = pd.DataFrame({
    'region_id': [1, 2, 3],
    'region_name': ['North', 'South', 'East']
})

df_region2 = pd.DataFrame({
    'region_id': [4, 5, 6],
    'region_name': ['West', 'Central', 'North']
})

df_combined = pd.concat([df_region1, df_region2], ignore_index = True)
print(df_combined)

print('\n Horizantal combine')
df_combined1 = pd.concat([df_region1, df_region2], axis = 1, ignore_index = True)
print(df_combined1)

   region_id region_name
0          1       North
1          2       South
2          3        East
3          4        West
4          5     Central
5          6       North

 Horizantal combine
   0      1  2        3
0  1  North  4     West
1  2  South  5  Central
2  3   East  6    North
